# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.30
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21607235966
# Commit: https://github.com/zenopie/erth-network-app/commit/cb2d5e8e18e9e062ee799b206b5e6e0d8a9a8530
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:a191a840ee64b5fc47151f3f4496f9ce8b1a1f18efffe1021dd97ddffbc6ac46
    ports:
      - '80'
