# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.33
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21620944895
# Commit: https://github.com/zenopie/erth-network-app/commit/f160479aa754f8561168d52f7101aae86ff06f67
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:9414c67032b012dbfb54ea32c326fc65dc950e1929357dbc8e8fda67efb4ec37
    ports:
      - '80'
