# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.28
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21576383134
# Commit: https://github.com/zenopie/erth-network-app/commit/ba215fb4b9145c3563fbf4ef12d4a05a0979e876
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:333a12dac2cfe393dbf354c91227a723f2ea3cf089b311de7eed3b83e6d44b2e
    ports:
      - '80'
