# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.35
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/22081947486
# Commit: https://github.com/zenopie/erth-network-app/commit/efbcd48488b912cbeee9efe3459bcd6a44ec3677
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:afa15f69482be651abfd55de7bd9f6a2368ec6aea87e8e470e0ea4add01327aa
    ports:
      - '80'
