# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.15
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19375809479
# Commit: https://github.com/zenopie/erth-network-app/commit/05e84d15f0a8c6d826a84af6954d6b5e538d4a31
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:2b6243171df6c164067e992ce76e876ad2970fbe6bdd558fcb9f05003204bdf1
    ports:
      - '80'
