# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.17
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19376577527
# Commit: https://github.com/zenopie/erth-network-app/commit/0ae219fe973bb7c34430a326af482392b6b04059
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:cbfcb553827adeca361a96bd0b0ec55b501fe8b4cc8e078389348ad23b99a5d6
    ports:
      - '80'
