# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.16
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19376273415
# Commit: https://github.com/zenopie/erth-network-app/commit/bdece542ab67fa35282366ae9dabce90cbd5fc8d
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:9c4bc0792a6b3ad316cb2d97f7bf4b4cbef9c2461f3503aafc845b4f85250880
    ports:
      - '80'
