# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.31
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21612742225
# Commit: https://github.com/zenopie/erth-network-app/commit/a0776c443909f7b0b0a7d1e05aa55770c1f4ff64
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:ee861e6dac7a9518bcb2f0ae6ceac2efd312ae0a74f948a0d3b3e8668f0e69ec
    ports:
      - '80'
