# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.22
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19547994984
# Commit: https://github.com/zenopie/erth-network-app/commit/2a61b0b36247b8c0e4bcb6368fe62f6e3996ceb8
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:e3ac4d91244ca4396f0f313f67b3e5045bf556a38c2b02c1ad8ae83c36efc8c2
    ports:
      - '80'
