# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.20
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19377225233
# Commit: https://github.com/zenopie/erth-network-app/commit/9734f79cec76f10c8112c98a32b320d290cba952
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:810e22b7655dadc374c5e1f6460b460104f84fee4d707dc830b6fedeebc238fb
    ports:
      - '80'
