# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.34
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21887543112
# Commit: https://github.com/zenopie/erth-network-app/commit/39bbd66790280b63d81317409e8174d4e741191b
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:8e353443d2de0ec2d9c93ee5c8cdd2bf8dc43ca1497d42f26b09705018e43a9f
    ports:
      - '80'
