# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.29
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21583311144
# Commit: https://github.com/zenopie/erth-network-app/commit/345d086619b3a6c742649ddeed4956d648eeed34
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:c2121af7334c8a28faa6c2b3ac817db48c4ed7ffdb55350df70b181abaa3c62d
    ports:
      - '80'
