# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.26
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21413036873
# Commit: https://github.com/zenopie/erth-network-app/commit/2e656d6787cc2b254d17cda4301ad173f4bd619f
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:787186a272a8400ea0e6e971ca4221ae063b241033d9545dc53ed28d484720ae
    ports:
      - '80'
