# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.24
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19715967892
# Commit: https://github.com/zenopie/erth-network-app/commit/05c64838bf067d97e3aa3676aebcbab3714397dc
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:0a89c38840fa677886ba11462a462e796d48e1d99582262bc7f560d660a8001a
    ports:
      - '80'
