# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.13
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19375300792
# Commit: https://github.com/zenopie/erth-network-app/commit/900399ac943b2c148686a79e5c26176f870d5c80
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:65c18da65717e553d14fc35e0bf620d6675fd864d3f4ef1f4a6373508b870f3f
    ports:
      - '80'
