# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.27
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/21499712681
# Commit: https://github.com/zenopie/erth-network-app/commit/67e536f6143de9a56feaeadbf88d1c156f55a84d
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:434c0918e0638b1d49e8d498c25050c5ac31a3a80fa2242d7bcef6f327034f69
    ports:
      - '80'
