# Release: https://github.com/zenopie/erth-network-app/releases/tag/v1.1.21
# Workflow URL: https://github.com/zenopie/erth-network-app/actions/runs/19547103973
# Commit: https://github.com/zenopie/erth-network-app/commit/4ef599a3147c3152279121e092e49ed3b8d04a55
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/erth-network-app@sha256:8ddc24a835c4d1164fe5e20a408eeb7e3b48c7bec3ba42b6194d4322fabd4e0f
    ports:
      - '80'
